ingredient_index:
    path:     /
    defaults: { _controller: "CaroGFaimBundle:ingredient:index" }
    methods:  GET

ingredient_show:
    path:     /{id}/show
    defaults: { _controller: "CaroGFaimBundle:ingredient:show" }
    methods:  GET

ingredient_new:
    path:     /new
    defaults: { _controller: "CaroGFaimBundle:ingredient:new" }
    methods:  [GET, POST]

ingredient_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaroGFaimBundle:ingredient:edit" }
    methods:  [GET, POST]

ingredient_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaroGFaimBundle:ingredient:delete" }
    methods:  DELETE
