personne_index:
    path:     /
    defaults: { _controller: "CaroGFaimBundle:personne:index" }
    methods:  GET

personne_show:
    path:     /{id}/show
    defaults: { _controller: "CaroGFaimBundle:personne:show" }
    methods:  GET

personne_new:
    path:     /new
    defaults: { _controller: "CaroGFaimBundle:personne:new" }
    methods:  [GET, POST]

personne_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaroGFaimBundle:personne:edit" }
    methods:  [GET, POST]

personne_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaroGFaimBundle:personne:delete" }
    methods:  DELETE
