type_plat_index:
    path:     /
    defaults: { _controller: "CaroGFaimBundle:type_plat:index" }
    methods:  GET

type_plat_show:
    path:     /{id}/show
    defaults: { _controller: "CaroGFaimBundle:type_plat:show" }
    methods:  GET

type_plat_new:
    path:     /new
    defaults: { _controller: "CaroGFaimBundle:type_plat:new" }
    methods:  [GET, POST]

type_plat_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaroGFaimBundle:type_plat:edit" }
    methods:  [GET, POST]

type_plat_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaroGFaimBundle:type_plat:delete" }
    methods:  DELETE
